####   Here we are going to use the secret for mysql root password by creating sercret and then mapping secret to the pod definition

#### Create encrypted code for the password you would like to use:
#### In the following example I have generated encrypted code for password - admin

# echo -n 'admin' | base64
YWRtaW4=

#### Add encrypted sting to the secret.yaml file as follows: 
####  Create file secret.yaml:

apiVersion: v1
kind: Secret
metadata:
  name: mysql-code
type: Opaque
data:
  password: YWRtaW4=
  
### Map this secret.yaml file 
### Create pod file - mysqlpods1.yaml as follows
### Pay attention to env section where I have not specified the password for the env MYSQL_ROOT_PASSWORD, and map secret mysql-code to to serectKeyRef.

apiVersion: v1
kind: Pod
metadata:
  name: my-mysql-s1
  labels:
spec:
  containers:
    - name: my-mysql-s1
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-code
              key: password

### Now get the ip address of the pod - my-mysql-s1 
### Check mysql connection using following command

# mysql -uroot -padmin -h<ip_address>

At this point we can connect to the mysql instance of 8.0.26 latest edition 
